---
CORE:
  BASE_DIR: /home/gpadmin/                                #Make sure the directory name ends with "/"
  TEMP_DIR: /temp/                                        #Make sure the directory name ends with "/"
  APPLICATION_NAME: gpdbinstall
DOWNLOAD:
  API_TOKEN: <API Token>
  DOWNLOAD_DIR: /download/                                #Make sure the directory name ends with "/"
INSTALL:
  ENV_DIR: /env/                                          #Make sure the directory name ends with "/"
  UNINTSALL_DIR: /uninstall/                              #Make sure the directory name ends with "/"
  MASTER_DATA_DIRECTORY: /data/master/                    #Make sure the directory name ends with "/"
  SEGMENT_DATA_DIRECTORY: /data/primary/                  #Make sure the directory name ends with "/"
  TOTAL_SEGMENT: 2
